---
- hosts: demo
  tasks:
        - name: Install nginx
          yum: name=nginx state=installed
        - name: Start nginx
          service: name=nginx state=started enabled=yes

        - name: Extract nginx.zip
          unarchive: src=/root/nginx.zip dest=/usr/share/nginx/html remote_src=yes

        - name: Replace line in index.html
          replace:
                path: /usr/share/nginx/html/index.html
                regexp: This is a sample html code
                replace: This is ansible playbook
